### ISSUE TITLE
Parse an Issue

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#103]
One of our original objectives with creating this module was to get all the issue in a given org and organise them in a single view. When GitHub changed the UI for issues last year our parser "broke" ... let's fix it now!

# Tasks

+ [ ] Go through each test in https://github.com/nelsonic/github-scraper/blob/master/test/issue.test.js and "unskip" one at a time making it pass by updating the selectors in https://github.com/nelsonic/github-scraper/blob/master/lib/issue.js
+ [ ] title
+ [ ] state (open/closed)
+ [ ] author (person who opened the issue)
+ [ ] created (date the issue was opened)
+ [ ] comments - get the list of comments
  + [ ] author - person who posted the comment
  + [ ] created - date when the comment was posted
  + [ ] body - the text of the comment
+ [ ] labels - the labels that are _currently_ applied to the issue
+ [ ] assignees - the array of people assigned to work on the issue
+ [ ] participants - array of people who have participated (commented) in the issue

Once we have this basic info we can work on the metadata contained in the page #43 
Related to #24 (_scrape an issue with a single comment_)

**Comment by iharshit009** [comment]
@nelsonic sir do i have to get the knowledge of node as well for this project??
currently  i am having good hands on python only..

**Comment by nelsonic** [comment]
Sticking with `view-source:https://github.com/dwyl/tudo/issues/51` as the example issue to parse as it appears to have enough comments and meta data.

**Comment by nelsonic** [comment]
@iharshit009 the Node.js in this project is quite basic and the majority of the business logic is JQuery-style DOM Selectors. If you are up for adding to your skills/CV with some Node.js/JavaScript please consider reading and running the code on your `localhost`. 👍
