### ISSUE TITLE
Feat: Deploy AWS Lambda Function with URL

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#128]
We need a way of invoking the scraper from our `Elixir` app for https://github.com/dwyl/who/issues/86

# Todo

+ [ ] allow a single `url` variable
+ [ ] return `data` as `JSON`

> **Note**: Only working on the "happy path". 

+ [ ] deploy to lambda using https://github.com/dwyl/aws-lambda-deploy
  + [ ] Update https://github.com/dwyl/aws-lambda-deploy in the process 😬 

Ref: https://github.com/dwyl/learn-aws-lambda/issues/124 -> https://dev.to/aws-builders/introducing-lambda-function-urls-4ahd

**Comment by nelsonic** [comment]
Getting a roadblock: 
```
distpath: tmp/dist/
node:child_process:965
    throw err;
    ^

Error: Command failed: zip -rq -X tmp/github-scraper.zip ./
    at checkExecSyncError (node:child_process:890:11)
    at Object.execSync (node:child_process:962:15)
    at module.exports (/Users/n/code/github-scraper/node_modules/dpl/lib/exec_sync.js:5:23)
    at Object.zip (/Users/n/code/github-scraper/node_modules/dpl/lib/zip.js:19:3)
    at Object.<anonymous> (/Users/n/code/github-scraper/node_modules/dpl/dpl.js:12:5)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12) {
  status: 15,
  signal: null,
  output: [
    null,
    'zip I/O error: No such file or directory\n' +
      'zip error: Could not create output file (tmp/github-scraper.zip)\n',
    ''
  ],
  pid: 63403,
  stdout: 'zip I/O error: No such file or directory\n' +
    'zip error: Could not create output file (tmp/github-scraper.zip)\n',
  stderr: ''
}

Node.js v20.11.0
```

**Comment by nelsonic** [comment]
Working: 
https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/github-scraper-v7?tab=testing
<img width="1477" alt="image" src="https://github.com/nelsonic/github-scraper/assets/194400/3e411629-94d0-4b81-b1ad-3ff51202b73a">

But I'm burning the candle at both ends working at 3am ... so calling it a day. 🛌

**Comment by nelsonic** [comment]
https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/github-scraper-v7?tab=testing
<img width="1562" alt="image" src="https://github.com/nelsonic/github-scraper/assets/194400/c0c4c6f5-0814-4af0-88e0-445142cfb73c">

```json
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module '../config/repos'\nRequire stack:\n- /var/task/lib/followers.js\n- /var/task/lib/scrapers.js\n- /var/task/lib/switcher.js\n- /var/task/lib/index.js\n- /var/task/index.js\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module '../config/repos'",
    "Require stack:",
    "- /var/task/lib/followers.js",
    "- /var/task/lib/scrapers.js",
    "- /var/task/lib/switcher.js",
    "- /var/task/lib/index.js",
    "- /var/task/index.js",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)",
    "    at async start (file:///var/runtime/index.mjs:1282:23)",
    "    at async file:///var/runtime/index.mjs:1288:1"
  ]
}
```

**Comment by nelsonic** [comment]
Basic lambda function is working: 
<img width="1552" alt="image" src="https://github.com/nelsonic/github-scraper/assets/194400/9c951457-5a8c-44c9-8c2a-75fa225898c7">

**Comment by nelsonic** [comment]
Working! 🎉 
<img width="728" alt="image" src="https://github.com/nelsonic/github-scraper/assets/194400/8ff05499-4fec-4f89-98b7-85e30f9621a2">

Not sharing the URL just yet as want to avoid spam. But I'm optimistic this will work. 💭

**Comment by nelsonic** [comment]
This is _already_ what I needed ...

<img width="752" alt="image" src="https://github.com/nelsonic/github-scraper/assets/194400/2dc66f6d-63d4-4b79-943e-39fd9accf0f1">

Now I need to _use_ it ... 💭
