### ISSUE TITLE
Re-Write Profile Parser

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/github-scraper#77]
Given GitHub's decision to re-do the Profile page ... e.g:
![image](https://user-images.githubusercontent.com/194400/27255074-2d62ada2-538e-11e7-9c75-9bf48ba01a76.png)

We need to re-write our parser for the page ....

# TODO
+ [x] `img`
+ [x] (github) `user_id` (_from image url_)
+ [x] `followers` (count)
+ [x] `following` (count)
+ [x] `stars` (count)
+ [x] `repos` (count)
+ [x] `pinned` Repositories (array)
+ [x] `organization` (name)
+ [x] `location`
+ [x] `contributions` (count)
+ [x] `fullname`
+ [x] `public_orgs` Organisations (on their profile)!!
